from enum import IntEnum


class ExitCode(IntEnum):
    SUCCESS = 0
    BOOTSTRAP_PATH_FAILURE = 10
    RUNTIME_NOT_WRITABLE = 11
    QT_INITIALIZATION_FAILURE = 20
    QML_ROOT_LOAD_FAILURE = 21
    DEPENDENCY_RUNTIME_MISMATCH = 30
    UNEXPECTED_FATAL = 99
